// Licence: GPLv3 & GPLv2 (dual licensed)
// Original source: https://github.com/Ladsgroup/CheckUserHelper
'use strict';

/**
 * Adds a button underneath the summary table that when
 * pressed adds the table in a wikitext format to the
 * clipboard of the user.
 *
 * @param {string} copyText The wikitext table to copied (generated by createTableText.js)
 */
function addCopyElement( copyText ) {
	// eslint-disable-next-line compat/compat
	if ( !navigator.clipboard || !navigator.clipboard.writeText ) {
		return;
	}

	const copyButton = new OO.ui.ButtonWidget( {
		label: mw.msg( 'ooui-copytextlayout-copy' ),
		icon: 'copy'
	} );

	copyButton.$element.addClass( 'mw-checkuser-helper-copy-button' );
	copyButton.on( 'click', () => {
		copyButton.setDisabled( true );

		// eslint-disable-next-line compat/compat
		navigator.clipboard.writeText( copyText ).then( () => {
			mw.notify(
				mw.msg( 'checkuser-helper-copy-success' ),
				{ type: 'success' }
			);
		} ).catch( ( e ) => {
			mw.errorLogger.logError( e, 'error.checkuser' );
			mw.notify(
				mw.msg( 'checkuser-helper-copy-failed' ),
				{ type: 'error' }
			);
		} ).then( () => {
			copyButton.setDisabled( false );
		} );
	} );

	$( '.mw-checkuser-helper-table' ).after( copyButton.$element );
}

module.exports = addCopyElement;
