-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case_property-drop-sicp_stale.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__cusi_case_property AS
SELECT
  sicp_sic_id,
  sicp_property,
  sicp_value
FROM /*_*/cusi_case_property;

DROP TABLE /*_*/cusi_case_property;


CREATE TABLE /*_*/cusi_case_property (
  sicp_sic_id INTEGER UNSIGNED NOT NULL,
  sicp_property SMALLINT UNSIGNED NOT NULL,
  sicp_value DOUBLE PRECISION NOT NULL,
  PRIMARY KEY(sicp_sic_id, sicp_property)
);

INSERT INTO /*_*/cusi_case_property (
  sicp_sic_id, sicp_property, sicp_value
)
SELECT
  sicp_sic_id,
  sicp_property,
  sicp_value
FROM /*_*/__temp__cusi_case_property;

DROP TABLE /*_*/__temp__cusi_case_property;
