-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case_property-def.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cusi_case_property (
  sicp_sic_id INTEGER UNSIGNED NOT NULL,
  sicp_property SMALLINT UNSIGNED NOT NULL,
  sicp_value DOUBLE PRECISION NOT NULL,
  sicp_stale SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(sicp_sic_id, sicp_property)
);
