-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/CheckUser/schema/abstractSchemaChanges/patch-cu_log-defaults.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  cu_log ALTER cul_user
SET  DEFAULT 0;
ALTER TABLE  cu_log ALTER cul_user_text
SET  DEFAULT '';